name: Docker Build and Push Image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push aspnetcore 3.1 image
        uses: docker/build-push-action@v2
        with:
          file: ./aspnet/3.1/Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: martinussuherman/alpine-dotnet:3.1

      - name: Build and push aspnet 5.0 image
        uses: docker/build-push-action@v2
        with:
          file: ./aspnet/5.0/Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: martinussuherman/alpine-dotnet:5.0
